main: com.kryeit.Teleposte
version: 2.1
name: Teleposte
description: Postes para conectar con la gente!
author: MuriPlz
softdepend: [GriefDefender,StructureBlockLib]
api-version: 1.18
commands:
  poste:
    description: te muestra el poste más cercano
    aliases: postecercano
  mudarse:
    description: hace del poste más cercano tu casa
  invitar:
    description: invita a un jugador a tu casa
  casa:
    description: te teletransporta a tu casa
    aliases: c
  visitar:
    description: visita un poste
    aliases: v
  nombrarposte:
    description: nombra un poste
  desnombrarposte:
    description: desnombra un poste
    permission: telepost.unnamepost
  listapostes:
    description: muestra los postes con nombre, y te deja clicarlos
  dumpdb:
    description: Dumps the database
    permission: telepost.dumpdb
  protegerpostes:
    description: protege automaticamente todos los postes del mundo
    permission: telepost.claimposts
  construirpostes:
    description: construye todos los postes del mundo
    permission: telepost.buildposts
  forzarvisita:
    description: fuerza la visita de un jugador a un poste
    permission: telepost.forcevisit